version: "3"
services:
  client:
    image: "cyebukayire/work:client"
    mem_limit: 128m
    hostname: client
    ports:
      - "3000:3000"
  server:
    image: "cyebukayire/work:server"
    mem_limit: 128m
    hostname: api
    environment:

      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
      # - REDIS_HOST=$REDIS_HOST
      # - REDIS_PORT=$REDIS_PORT
      # - PGUSER=$PGUSER
      # - PGHOST=$PGHOST
      # - PGDATABASE=$PGDATABASE
      # - PGPASSWORD=$PGPASSWORD
      # - PGPORT=$PGPORT
    ports:
      do- "5000:5000"

  worker:
    image: "cyebukayire/work:worker"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  nginx:
    image: "cyebukayire/nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"





