# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - worker-app

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_d03aacf289764fe98d71c040e5490418 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_8f0b2691cc3f4a9bb380373fc6730ff9 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_d03aacf289764fe98d71c040e5490418 }}/work:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'worker-app'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_29ec9f53e7284e6fbcf1af16f6293c34 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_d03aacf289764fe98d71c040e5490418 }}/work:${{ github.sha }}'